### ISSUE TITLE
Question about "Proj_Img" class

### ISSUE THREAD

**Issue by Gyu007** [ChiShengChen/MUSE_EEG#3]
Hello. I was analyzing your public code to use it for my research. I have a question about the "Proj_img" class. When I looked at the training code, I saw that this class uses the default values ​​set for the class, and I can see that embedding_dim and projection_dim are the same. Since it does not adjust the size of the embedding vector, I wonder if Proj_img is damaging the embedding space of the pre-trained image encoder model, so I would like to hear an answer to this question.

**Comment by ChiShengChen** [comment]
Hi @gyuseok0917 :
You are correct that in the current implementation, the default values for embedding_dim and projection_dim are set to the same value, which means that no dimensionality reduction or transformation is applied to the image embedding vectors. This design was intentional for the following reasons:

(a) Preserving Pre-trained Embedding Space:
The pre-trained image encoder we used (e.g., CLIP-ViT) has been extensively trained to produce high-quality embeddings that align well with the feature space of natural images. By not altering the dimensionality of these embeddings, we aim to retain their integrity and ensure that their semantic information remains unaltered during training.

(b) Avoiding Potential Damage to Embedding Space:
As you noted, applying an unnecessary projection layer could potentially distort the embedding space and reduce the quality of alignment between the image and EEG embeddings. By default, the Proj_img class is designed to act as an identity mapping when embedding_dim equals projection_dim. This avoids introducing noise or transformation that could harm the pre-trained embeddings.


While the current configuration works well in our experiments, there are scenarios where adjusting the dimensions might be beneficial:

(a) Cross-Modality Alignment: If the EEG embeddings are of a different dimension, projecting both image and EEG embeddings into a shared space can improve alignment.
(b) Domain-Specific Fine-Tuning: For certain tasks or datasets, reducing dimensionality might help focus on the most relevant features, though care must be taken to ensure that the projection layer is properly trained.
In such cases, the Proj_img class allows flexibility to adjust projection_dim as needed. However, in the default configuration, preserving the original embedding dimensionality aligns with the goal of minimizing disruption to the pre-trained image encoder's embedding space.

Thank you again for your thoughtful question! If you have further queries or would like assistance adapting the code for your research, feel free to reach out.
